GCAL_USERNAME="somebody@example.com"
GCAL_PASSWORD="password"
GCAL_ID="default"

MC_API_KEY="api-key-here"
MC_LIST_ID="list-id-here"
MC_EMAIL="somebody@example.com"
MC_FROM_NAME="Joe Somebody"
MC_TO_NAME="Joe's ListServ"
MC_TEMPLATE_SECTION="std_content00"
MC_TEMPLATE_NAME="Joes Template"


# There are message templates for html and text, which vary based on the number of times available

EVENT_TEMPLATE = {}
EVENT_TEMPLATE['HTML_TITLE'] = "<h3>{title}</h3>\n"
EVENT_TEMPLATE['TEXT_TITLE'] = "{title}\n"
EVENT_TEMPLATE['HTML_START_DATE'] = "<h4>{start_date}"
EVENT_TEMPLATE['TEXT_START_DATE'] = "{start_date}"
EVENT_TEMPLATE['START_TIME'] = "{start_time}"
EVENT_TEMPLATE['END_DATE'] = "{end_date}"
EVENT_TEMPLATE['END_TIME'] = "{end_time}"
EVENT_TEMPLATE['HTML_LOC'] = " at {location}</h4>\n"
EVENT_TEMPLATE['HTML_DESC'] = "<p>{description}</p>"
EVENT_TEMPLATE['TEXT_LOC'] = " at {location}\n"
EVENT_TEMPLATE['TEXT_DESC'] = "{description}"

EVENT_HTML_TEMPLATE_WITH_ALL = (EVENT_TEMPLATE['HTML_TITLE'] + EVENT_TEMPLATE['HTML_START_DATE'] + " ," + EVENT_TEMPLATE['START_TIME'] + " &mdash; " + EVENT_TEMPLATE['END_DATE'] + ", " + EVENT_TEMPLATE['END_TIME'] + EVENT_TEMPLATE['HTML_LOC']+ EVENT_TEMPLATE['HTML_DESC'])

EVENT_HTML_TEMPLATE_DEFAULT = (EVENT_TEMPLATE['HTML_TITLE'] + EVENT_TEMPLATE['HTML_START_DATE'] + ", " +  EVENT_TEMPLATE['START_TIME'] + " &mdash; " + EVENT_TEMPLATE['END_TIME'] + EVENT_TEMPLATE['HTML_LOC'] + EVENT_TEMPLATE['HTML_DESC'])

EVENT_HTML_TEMPLATE_NO_TIMES = (EVENT_TEMPLATE['HTML_TITLE'] + EVENT_TEMPLATE['HTML_START_DATE']+ " &mdash; " + EVENT_TEMPLATE['END_DATE'] + EVENT_TEMPLATE['HTML_LOC'] + EVENT_TEMPLATE['HTML_DESC']) 

EVENT_TEXT_TEMPLATE_DEFAULT = EVENT_TEMPLATE['TEXT_TITLE'] + EVENT_TEMPLATE['TEXT_START_DATE'] + ", " + EVENT_TEMPLATE['START_TIME'] + " &mdash; " + EVENT_TEMPLATE['END_TIME'] + EVENT_TEMPLATE['TEXT_LOC'] + EVENT_TEMPLATE['TEXT_DESC']

EVENT_TEXT_TEMPLATE_NO_TIMES = (EVENT_TEMPLATE['TEXT_TITLE'] + EVENT_TEMPLATE['TEXT_START_DATE']+ " &mdash; " + EVENT_TEMPLATE['END_DATE'] + EVENT_TEMPLATE['TEXT_LOC'] + EVENT_TEMPLATE['TEXT_DESC']) 

EVENT_TEXT_TEMPLATE_WITH_ALL = (EVENT_TEMPLATE['TEXT_TITLE'] + EVENT_TEMPLATE['TEXT_START_DATE'] + ", " + EVENT_TEMPLATE['START_TIME'] +  " &mdash; " + EVENT_TEMPLATE['END_DATE'] + ", " + EVENT_TEMPLATE['END_TIME'] + EVENT_TEMPLATE['TEXT_LOC'] + EVENT_TEMPLATE['TEXT_DESC'])

SUBJECT_TEMPLATE = "ADI Newsletter %m/%d/%Y"

DATE_FORMAT = '%A, %m/%d'
TIME_FORMAT = '%I:%M %p'

